Repository 25-HF003/back-end, pull requests merged in 2025-08, with the labels that each got.

#51 Feat: 워터마크 삽입 이미지 Flask 연동 및 S3 업로드 기능 추가
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/watermark/WatermarkFlaskResponseDTO.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkService.java
Labels: ✨ Feature

#54 ETR-62 JWT Access/Refresh 토큰 구조 리팩토링
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/login/LoginResponse.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/login/RefreshTokenRequest.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/user/UserProfile.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/config/JwtAuthenticationFilter.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/config/SecurityConfig.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/UserController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/entity/RefreshToken.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/repository/RefreshTokenRepository.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/UserService.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/util/JwtUtil.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/controller/UserControllerTest.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/service/UserServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#52 Refactor: 워터마크 전체 조회 API에 15건 단위 페이징 기능 추가
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/repository/WatermarkRepository.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkService.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/controller/WatermarkControllerTest.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/service/WatermarkServiceTest.java
Labels: 🔨 Refactor

#53 Refactor: 딥페이크 전체 조회 API에 15건 단위 페이징 기능 추가
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/repository/DeepfakeDetectionRepository.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionControllerTest.java
Labels: 🔨 Refactor

#61 originalFilePath 필드 제거 및 JWT 인증 적용
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/watermark/WatermarkDTO.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/entity/Watermark.java
Labels: 🔨 Refactor

#64 Refactor:JWT 인증 추가
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionController.java
Labels: 🔨 Refactor

#66 Feat: 커스텀 예외 추가 및 GlobalExceptionHandler 구현; Refacotr: 에러 처리를 위한 deepfake & watermark service 수정
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/DetectionNotFoundException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/ExternalServiceException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/GlobalExceptionHandler.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/ImageDecodingException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/InvalidDetectionResponseException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/InvalidFileException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/InvalidWatermarkResponseException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/StorageException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/UserNotFoundException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/WatermarkNotFoundException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/repository/DeepfakeDetectionRepository.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/repository/WatermarkRepository.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkService.java
Labels: ✨ Feature, 🔨 Refactor

#71 Feat: 적대적 노이즈 생성 백엔드 API 및 S3 통합 구현 (ETR-79)
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/noise/NoiseCreateRequestDTO.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/noise/NoiseDTO.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/noise/NoiseFlaskResponseDTO.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/InvalidNoiseResponseException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/NoiseNotFoundException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/NoiseController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/entity/Noise.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/repository/NoiseRepository.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/NoiseService.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionControllerTest.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/service/DeepfakeDetectionServiceTest.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/service/NoiseServiceTest.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/service/WatermarkServiceTest.java
Labels: ✨ Feature, ✅ Test

#85 Fix: Deepfake 응답에 정밀모드 옵션 추가
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/Enum/DeepfakeDetector.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/Enum/DeepfakeMode.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/deepfake/DeepfakeDetectionDTO.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/deepfake/FlaskResponseDTO.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/entity/DeepfakeDetection.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java
Labels: 🔨 Refactor

#88 Feat: 적대적 노이즈 자동/정밀 모드 mode, level 필드 연동 및 히스토리 API 반영
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/noise/NoiseDTO.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/noise/NoiseFlaskResponseDTO.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/NoiseController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/entity/Noise.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/NoiseService.java
Labels: ✨ Feature
