Repository 25-HF003/back-end, pull requests merged in 2025-09, with the labels that each got.

#98 Refactor: 예외 처리 체계화 및 인증 방식 통일
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/DuplicateLoginIdException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/GlobalExceptionHandler.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/NoiseController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/UserController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkDetectionController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/UserService.java
Labels: ✨ Feature, 🔨 Refactor

#100 Feat: Deepfake 및 Watermark, S3 서비스에 관련된 전역 예외 처리 도입
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/ArtifactNotFoundException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/DataCorruptionException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/DataMappingException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/FileEmptyException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/GlobalExceptionHandler.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/InvalidEnumValueException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/InvalidFilenameException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/S3UploadFailedException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/SimilarityThresholdExceededException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/UnauthorizedException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/UnsupportedMediaTypeException.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/WatermarkDetectionController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/AmazonS3Service.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkDetectionService.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkService.java
Labels: ✨ Feature, 🔨 Refactor

#101 Feat: 회원 데이터 자동 정리 시스템 구현
  deeptruth/src/main/java/com/deeptruth/deeptruth/DeeptruthApplication.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/exception/GlobalExceptionHandler.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/constants/LoginConstants.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/UserController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/repository/DeepfakeDetectionRepository.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/repository/NoiseRepository.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/repository/UserRepository.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/repository/WatermarkRepository.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/scheduler/UserCleanupScheduler.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/NoiseService.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/UserService.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/controller/WatermarkControllerTest.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/scheduler/UserCleanupSchedulerTest.java
Labels: ✨ Feature, ✅ Test, 🔨 Refactor

#106 Test: 워터마크 서비스, 컨트롤러 테스트 수정 및 WithMockCustomUser 생성
  deeptruth/build.gradle
  deeptruth/src/test/java/com/deeptruth/deeptruth/controller/WatermarkControllerTest.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/service/WatermarkServiceTest.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/testsecurity/WithMockCustomUser.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/testsecurity/WithMockCustomUserSecurityContextFactory.java
Labels: ✅ Test

#109 Test: Deepfake 서비스/컨트롤러 테스트 추가
  deeptruth/src/test/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionControllerTest.java
  deeptruth/src/test/java/com/deeptruth/deeptruth/service/DeepfakeDetectionServiceTest.java
Labels: ✅ Test

#111 Fix: pHash 임계값 변경
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/WatermarkDetectionService.java
Labels: 🔨 Refactor

#114 Feat: 적대적 노이즈 실시간 진행률 연동 및 보안 정책 개선
  deeptruth/src/main/java/com/deeptruth/deeptruth/config/SecurityConfig.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/config/WebConfig.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/NoiseController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/NoiseService.java
Labels: ✨ Feature, 🔨 Refactor
