Repository 25-HF003/back-end, pull requests merged in 2025-10, with the labels that each got.

#119 Feat: ALB 헬스체크를 위한 Spring Boot Actuator 설정
  deeptruth/build.gradle
  deeptruth/src/main/java/com/deeptruth/deeptruth/config/SecurityConfig.java
Labels: 🌏 Deploy, ✨ Feature

#120 Refactor: SecurityConfig에 CORS 설정 연동 추가
  deeptruth/src/main/java/com/deeptruth/deeptruth/config/SecurityConfig.java
Labels: 🌏 Deploy, 🔨 Refactor

#123 Feat: 웹소켓 convertAndSendToUser 사용자 식별을 위한 HttpSessionHandshakeInterce…
  deeptruth/src/main/java/com/deeptruth/deeptruth/config/WebSocketConfig.java
Labels: ✨ Feature, 🔨 Refactor

#124 Fix: 웹소켓 전송 경로 변경
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/ProgressController.java
Labels: 🔨 Refactor

#125 Feat:RabbitMQ 기반 비동기 딥페이크 탐지 파이프라인 도입 (Spring ↔ RabbitMQ ↔ Flask ↔ S3 ↔ WebSocket)
  deeptruth/build.gradle
  deeptruth/src/main/java/com/deeptruth/deeptruth/DeeptruthApplication.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/websocket/DeepfakeRequestMessage.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/websocket/TaskAcceptedDTO.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/base/dto/websocket/TaskEvent.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/config/RabbitConfig.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/config/WebSocketConfig.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/controller/DeepfakeDetectionController.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/AmazonS3Service.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/service/DeepfakeDetectionService.java
  deeptruth/src/main/java/com/deeptruth/deeptruth/worker/DeepfakeWorker.java
Labels: ✨ Feature
